# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_profile', '0003_remove_libprofile_books_issued'),
        ('admin_interface', '0003_auto_20150920_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='issued',
        ),
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, to='admin_interface.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(blank=True, null=True, to='admin_interface.Publisher'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Book'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_profile.libprofile'),
        ),
        migrations.AddField(
            model_name='issuedlog',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Book'),
        ),
        migrations.AddField(
            model_name='issuedlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_profile.libprofile'),
        ),
    ]
